require:
  - rubocop-performance

AllCops:
  Exclude:
    - tmp/**/*
    - vendor/**/*
  DisplayCopNames: true
  TargetRubyVersion: 2.4

# Use older RuboCop default
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': ()

# SupportedStyles: percent, brackets
Style/SymbolArray:
  EnforcedStyle: brackets

# Code is currently broken with frozen string literal comments applied.
# TODO: Enable and fix build
Style/FrozenStringLiteralComment:
  Enabled: false

# TODO: This is placed in here so the auto-gen-config doesn't destroy these.
# Most of these need to be manually tackled, the LineLength value currently is good enough to stop most of
# these leaking through into the codebase
# Offense count: 375+
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 100

# We only permit it in this one area which is internal code testing. Never exposed to users
Security/Eval:
  Exclude:
    - spec/support/helpers/reporting.rb

inherit_from: .rubocop_todo.yml
