require:
  - rubocop-performance

AllCops:
  Exclude:
    - tmp/**/*
    - vendor/**/*
  DisplayCopNames: true
  TargetRubyVersion: 2.4

# Use older RuboCop default
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': ()

# SupportedStyles: percent, brackets
Style/SymbolArray:
  EnforcedStyle: brackets

# Code is currently broken with frozen string literal comments applied.
# TODO: Enable and fix build
Style/FrozenStringLiteralComment:
  Enabled: false

# Be relatively lenient with line length
Layout/LineLength:
  Max: 94

# We only permit it in this one area which is internal code testing. Never exposed to users
Security/Eval:
  Exclude:
    - spec/support/helpers/reporting.rb

inherit_from: .rubocop_todo.yml
