require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - tmp/**/*
    - vendor/**/*
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 2.5

# Ignore gemfiles created by Appraisal
Bundler/OrderedGems:
  Exclude:
    - 'gemfiles/*.gemfile'

# Spec blocks can be any size
Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - 'spec/**/*'

# This cop does not work properly with predicates that take arguments.
# TODO: Re-enable once https://github.com/rubocop/rubocop-rspec/issues/466 is resolved.
RSpec/PredicateMatcher:
  Enabled: false

# Use older RuboCop default
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': ()

# Do not commit to use of interpolation
Style/StringLiterals:
  EnforcedStyle: double_quotes

# SupportedStyles: percent, brackets
Style/SymbolArray:
  EnforcedStyle: brackets

# Code is currently broken with frozen string literal comments applied.
# TODO: Enable and fix build
Style/FrozenStringLiteralComment:
  Enabled: false

# Be relatively lenient with line length
Layout/LineLength:
  Max: 94

inherit_from: .rubocop_todo.yml
