# This workflow will download a prebuilt Ruby version, install dependencies and
# run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CUCUMBER_PUBLISH_QUIET: true
  JRUBY_OPTS: "--dev"

jobs:
  test-ubuntu:
    strategy:
      matrix:
        ruby: [2.4.0, 2.4, 2.5, 2.6, 2.7, "3.0", jruby-9.2, ruby-head]

    runs-on: ubuntu-latest

    continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake

  test-macos:
    strategy:
      matrix:
        ruby: [2.4, 2.5, 2.6, 2.7, "3.0"]

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Run linters
      run: bundle exec rake lint
