# This workflow will download a prebuilt Ruby version, install dependencies and
# run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CUCUMBER_PUBLISH_QUIET: true
  JRUBY_OPTS: "--dev"

jobs:
  test-ubuntu:
    strategy:
      matrix:
        ruby: [2.4.0, 2.4, 2.5, 2.6, 2.7, "3.0", jruby-9.2]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Configure bundler globally
      run: bundle config --global path $PWD/vendor/bundle
    - name: Run specs
      run: bundle exec rake spec
    - name: Run cukes
      run: bundle exec rake cucumber

  test-macos:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.4, 2.5, 2.6, 2.7, "3.0"]

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run specs
      run: bundle exec rake spec
    - name: Run cukes
      run: bundle exec rake cucumber

  checks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Install license_finder
      run: gem install license_finder
    - name: Run linters
      run: bundle exec rake lint
    - name: Run license_finder
      run: license_finder
